name: Sentry Release

on:
  release:
    types: [created]

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        with:
          auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          version: ${{ github.event.release.tag_name }}
